apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/part-of: kwetter
  name: redis-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kwetter
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '*'
    chart: redis-cluster
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
